/**
 * HISTORICAL — NEVER EDIT.
 *
 * These are the 94 built-in exercise names exactly as they existed when
 * migration 0004 introduced the `slug` column, paired with the slug that
 * migration assigns them.
 *
 * The seed replays this reconciliation as belt-and-braces for a database that
 * got the column via `db:push` rather than through the migration. That is the
 * only reason it exists.
 *
 * If a display name changes, change `name` in the seed data and leave this
 * file alone: the slug is the identity, the name is just what we render.
 */
export const LEGACY_NAME_TO_SLUG: ReadonlyArray<readonly [string, string]> = [
  ["Bench Press (Barbell)", "bench-press-barbell"],
  ["Bench Press (Dumbbell)", "bench-press-dumbbell"],
  ["Incline Bench Press (Barbell)", "incline-bench-press-barbell"],
  ["Incline Bench Press (Dumbbell)", "incline-bench-press-dumbbell"],
  ["Decline Bench Press (Barbell)", "decline-bench-press-barbell"],
  ["Chest Press (Machine)", "chest-press-machine"],
  ["Chest Fly (Dumbbell)", "chest-fly-dumbbell"],
  ["Cable Fly", "cable-fly"],
  ["Pec Deck", "pec-deck"],
  ["Push Up", "push-up"],
  ["Dip (Chest)", "dip-chest"],
  ["Deadlift (Barbell)", "deadlift-barbell"],
  ["Romanian Deadlift (Barbell)", "romanian-deadlift-barbell"],
  ["Pull Up", "pull-up"],
  ["Chin Up", "chin-up"],
  ["Lat Pulldown (Cable)", "lat-pulldown-cable"],
  ["Seated Row (Cable)", "seated-row-cable"],
  ["Bent Over Row (Barbell)", "bent-over-row-barbell"],
  ["Bent Over Row (Dumbbell)", "bent-over-row-dumbbell"],
  ["T-Bar Row", "t-bar-row"],
  ["Chest Supported Row (Machine)", "chest-supported-row-machine"],
  ["Straight Arm Pulldown", "straight-arm-pulldown"],
  ["Face Pull", "face-pull"],
  ["Shrug (Barbell)", "shrug-barbell"],
  ["Shrug (Dumbbell)", "shrug-dumbbell"],
  ["Back Extension", "back-extension"],
  ["Overhead Press (Barbell)", "overhead-press-barbell"],
  ["Overhead Press (Dumbbell)", "overhead-press-dumbbell"],
  ["Arnold Press", "arnold-press"],
  ["Shoulder Press (Machine)", "shoulder-press-machine"],
  ["Lateral Raise (Dumbbell)", "lateral-raise-dumbbell"],
  ["Lateral Raise (Cable)", "lateral-raise-cable"],
  ["Rear Delt Fly (Dumbbell)", "rear-delt-fly-dumbbell"],
  ["Rear Delt Fly (Machine)", "rear-delt-fly-machine"],
  ["Front Raise (Dumbbell)", "front-raise-dumbbell"],
  ["Upright Row (Barbell)", "upright-row-barbell"],
  ["Bicep Curl (Barbell)", "bicep-curl-barbell"],
  ["Bicep Curl (Dumbbell)", "bicep-curl-dumbbell"],
  ["Hammer Curl (Dumbbell)", "hammer-curl-dumbbell"],
  ["Preacher Curl", "preacher-curl"],
  ["Incline Curl (Dumbbell)", "incline-curl-dumbbell"],
  ["Cable Curl", "cable-curl"],
  ["Concentration Curl", "concentration-curl"],
  ["Tricep Pushdown (Cable)", "tricep-pushdown-cable"],
  ["Overhead Tricep Extension (Dumbbell)", "overhead-tricep-extension-dumbbell"],
  ["Skull Crusher (Barbell)", "skull-crusher-barbell"],
  ["Close Grip Bench Press", "close-grip-bench-press"],
  ["Dip (Triceps)", "dip-triceps"],
  ["Tricep Kickback", "tricep-kickback"],
  ["Wrist Curl", "wrist-curl"],
  ["Farmer's Walk", "farmers-walk"],
  ["Squat (Barbell)", "squat-barbell"],
  ["Front Squat (Barbell)", "front-squat-barbell"],
  ["Squat (Smith Machine)", "squat-smith-machine"],
  ["Hack Squat", "hack-squat"],
  ["Leg Press", "leg-press"],
  ["Bulgarian Split Squat", "bulgarian-split-squat"],
  ["Lunge (Dumbbell)", "lunge-dumbbell"],
  ["Goblet Squat", "goblet-squat"],
  ["Leg Extension", "leg-extension"],
  ["Leg Curl (Lying)", "leg-curl-lying"],
  ["Leg Curl (Seated)", "leg-curl-seated"],
  ["Good Morning", "good-morning"],
  ["Hip Thrust (Barbell)", "hip-thrust-barbell"],
  ["Glute Bridge", "glute-bridge"],
  ["Cable Kickback", "cable-kickback"],
  ["Hip Abduction (Machine)", "hip-abduction-machine"],
  ["Calf Raise (Standing)", "calf-raise-standing"],
  ["Calf Raise (Seated)", "calf-raise-seated"],
  ["Calf Press (Leg Press)", "calf-press-leg-press"],
  ["Plank", "plank"],
  ["Hanging Leg Raise", "hanging-leg-raise"],
  ["Cable Crunch", "cable-crunch"],
  ["Crunch", "crunch"],
  ["Sit Up", "sit-up"],
  ["Russian Twist", "russian-twist"],
  ["Ab Wheel Rollout", "ab-wheel-rollout"],
  ["Side Plank", "side-plank"],
  ["Woodchopper (Cable)", "woodchopper-cable"],
  ["Power Clean", "power-clean"],
  ["Clean and Jerk", "clean-and-jerk"],
  ["Snatch", "snatch"],
  ["Kettlebell Swing", "kettlebell-swing"],
  ["Thruster", "thruster"],
  ["Burpee", "burpee"],
  ["Treadmill Run", "treadmill-run"],
  ["Cycling", "cycling"],
  ["Rowing Machine", "rowing-machine"],
  ["Stair Climber", "stair-climber"],
  ["Elliptical", "elliptical"],
  ["Jump Rope", "jump-rope"],
  ["Battle Ropes", "battle-ropes"],
  ["Mountain Climbers", "mountain-climbers"],
  ["Sled Push", "sled-push"],
];
